schema_version = "1.0.0"

id = "gamecube_dat_model"
version = "3.1.0"
name = "Gamecube Dat Model"
tagline = "Import-Export Gamecube .dat models"
maintainer = "Made, StarsMmd, MikeyX"
type = "add-on"

[blender_version_min]
major = 4
minor = 5
patch = 0
