#subset of the GX header

GX_NOP =                      0x00
GX_DRAW_QUADS =               0x80
GX_DRAW_TRIANGLES =           0x90
GX_DRAW_TRIANGLE_STRIP =      0x98
GX_DRAW_TRIANGLE_FAN =        0xA0
GX_DRAW_LINES =               0xA8
GX_DRAW_LINE_STRIP =          0xB0
GX_DRAW_POINTS =              0xB8

GX_LOAD_BP_REG =              0x61
GX_LOAD_CP_REG =              0x08
GX_LOAD_XF_REG =              0x10
GX_LOAD_INDX_A =              0x20
GX_LOAD_INDX_B =              0x28
GX_LOAD_INDX_C =              0x30
GX_LOAD_INDX_D =              0x38

GX_CMD_CALL_DL =              0x40
GX_CMD_INVL_VC =              0x48

GX_OPCODE_MASK =              0xF8
GX_VAT_MASK =                 0x07


GX_TRUE =        (1)
GX_FALSE =       (0)
GX_ENABLE =      (1)
GX_DISABLE =     (0)

#GXTevOp
GX_TEV_ADD = 0
GX_TEV_SUB = 1

GX_TEV_COMP_R8_GT    = 8
GX_TEV_COMP_R8_EQ    = 9
GX_TEV_COMP_GR16_GT  = 10
GX_TEV_COMP_GR16_EQ  = 11
GX_TEV_COMP_BGR24_GT = 12
GX_TEV_COMP_BGR24_EQ = 13
GX_TEV_COMP_RGB8_GT  = 14
GX_TEV_COMP_RGB8_EQ  = 15

GX_TEV_COMP_A8_GT = GX_TEV_COMP_RGB8_GT
GX_TEV_COMP_A8_EQ = GX_TEV_COMP_RGB8_EQ

#GXTevBias
GX_TB_ZERO     = 0
GX_TB_ADDHALF  = 1
GX_TB_SUBHALF  = 2
GX_MAX_TEVBIAS = 3

#GXTevScale
GX_CS_SCALE_1   = 0
GX_CS_SCALE_2   = 1
GX_CS_SCALE_4   = 2
GX_CS_DIVIDE_2  = 3
GX_MAX_TEVSCALE = 4

#GXTevColorArg
GX_CC_CPREV = 0
GX_CC_APREV = 1
GX_CC_C0    = 2
GX_CC_A0    = 3
GX_CC_C1    = 4
GX_CC_A1    = 5
GX_CC_C2    = 6
GX_CC_A2    = 7
GX_CC_TEXC  = 8
GX_CC_TEXA  = 9
GX_CC_RASC  = 10
GX_CC_RASA  = 11
GX_CC_ONE   = 12
GX_CC_HALF  = 13
GX_CC_KONST = 14
GX_CC_ZERO  = 15

#GXTevAlphaArg
GX_CA_APREV = 0
GX_CA_A0    = 1
GX_CA_A1    = 2
GX_CA_A2    = 3
GX_CA_TEXA  = 4
GX_CA_RASA  = 5
GX_CA_KONST = 6
GX_CA_ZERO  = 7

#GXAttr
GX_VA_PNMTXIDX   = 0
GX_VA_TEX0MTXIDX = 1
GX_VA_TEX1MTXIDX = 2
GX_VA_TEX2MTXIDX = 3
GX_VA_TEX3MTXIDX = 4
GX_VA_TEX4MTXIDX = 5
GX_VA_TEX5MTXIDX = 6
GX_VA_TEX6MTXIDX = 7
GX_VA_TEX7MTXIDX = 8
GX_VA_POS        = 9
GX_VA_NRM        = 10
GX_VA_CLR0       = 11
GX_VA_CLR1       = 12
GX_VA_TEX0       = 13
GX_VA_TEX1       = 14
GX_VA_TEX2       = 15
GX_VA_TEX3       = 16
GX_VA_TEX4       = 17
GX_VA_TEX5       = 18
GX_VA_TEX6       = 19
GX_VA_TEX7       = 20

GX_POS_MTX_ARRAY = 21
GX_NRM_MTX_ARRAY = 22
GX_TEX_MTX_ARRAY = 23
GX_LIGHT_ARRAY   = 24
GX_VA_NBT        = 25
GX_VA_MAX_ATTR   = 26

GX_VA_NULL       = 0xff


#GXVtxFmt
GX_VTXFMT0       = 0
GX_VTXFMT1       = 1
GX_VTXFMT2       = 2
GX_VTXFMT3       = 3
GX_VTXFMT4       = 4
GX_VTXFMT5       = 5
GX_VTXFMT6       = 6
GX_VTXFMT7       = 7
GX_MAX_VTXFMT    = 8


#GXAttrType
GX_NONE    = 0
GX_DIRECT  = 1
GX_INDEX8  = 2
GX_INDEX16 = 3


#GXTexCoordID
GX_TEXCOORD0 = 0x0,
GX_TEXCOORD1 = 0x1
GX_TEXCOORD2 = 0x2
GX_TEXCOORD3 = 0x3
GX_TEXCOORD4 = 0x4
GX_TEXCOORD5 = 0x5
GX_TEXCOORD6 = 0x6
GX_TEXCOORD7 = 0x7
GX_MAX_TEXCOORD = 8
GX_TEXCOORD_NULL = 0xff


#GXTexGenType
GX_TG_MTX3x4 = 0
GX_TG_MTX2x4 = 1
GX_TG_BUMP0  = 2
GX_TG_BUMP1  = 3
GX_TG_BUMP2  = 4
GX_TG_BUMP3  = 5
GX_TG_BUMP4  = 6
GX_TG_BUMP5  = 7
GX_TG_BUMP6  = 8
GX_TG_BUMP7  = 9
GX_TG_SRTG   = 10


#GXTexGenSrc
GX_TG_POS = 0
GX_TG_NRM = 1
GX_TG_BINRM = 2
GX_TG_TANGENT = 3
GX_TG_TEX0 = 4
GX_TG_TEX1 = 5
GX_TG_TEX2 = 6
GX_TG_TEX3 = 4
GX_TG_TEX4 = 7
GX_TG_TEX5 = 8
GX_TG_TEX6 = 9
GX_TG_TEX7 = 10
GX_TG_TEXCOORD0 = 12
GX_TG_TEXCOORD1 = 13
GX_TG_TEXCOORD2 = 14
GX_TG_TEXCOORD3 = 15
GX_TG_TEXCOORD4 = 16
GX_TG_TEXCOORD5 = 17
GX_TG_TEXCOORD6 = 18
GX_TG_COLOR0 = 19
GX_TG_COLOR1 = 20


#GXCompCnt
GX_POS_XY    = 0
GX_POS_XYZ   = 1
GX_NRM_XYZ   = 0
GX_NRM_NBT   = 1
GX_NRM_NBT3  = 2
GX_CLR_RGB   = 0
GX_CLR_RGBA  = 1
GX_TEX_S     = 0
GX_TEX_ST    = 1


#GXCompType
GX_U8  = 0
GX_S8  = 1
GX_U16 = 2
GX_S16 = 3
GX_F32 = 4

GX_RGB565 = 0
GX_RGB8   = 1
GX_RGBX8  = 2
GX_RGBA4  = 3
GX_RGBA6  = 4
GX_RGBA8  = 5


#GXSpotFn
GX_SP_OFF = 0
GX_SP_FLAT = 1
GX_SP_COS = 2
GX_SP_COS2 = 3
GX_SP_SHARP = 4
GX_SP_RING1 = 5
GX_SP_RING2 = 6


#GXDistAttnFn
GX_DA_OFF = 0
GX_DA_GENTLE = 1
GX_DA_MEDIUM = 2
GX_DA_STEEP = 3


#GXPrimitive
GX_POINTS        = 0xb8
GX_LINES         = 0xa8
GX_LINESTRIP     = 0xb0
GX_TRIANGLES     = 0x90
GX_TRIANGLESTRIP = 0x98
GX_TRIANGLEFAN   = 0xa0
GX_QUADS         = 0x80


#GXTexWrapMode
GX_CLAMP = 0
GX_REPEAT = 1
GX_MIRROR = 2
GX_MAX_TEXWRAPMODE = 3


#GXTexFilter
GX_NEAR = 0
GX_LINEAR = 1
GX_NEAR_MIP_NEAR = 2
GX_LIN_MIP_NEAR = 3
GX_NEAR_MIP_LIN = 4
GX_LIN_MIP_LIN = 5


#GXCITexFmt
GX_TF_C4    = 0x8
GX_TF_C8    = 0x9
GX_TF_C14X2 = 0xa


#GXTexFmt
_GX_TF_CTF   = 0x20
_GX_TF_ZTF   = 0x10

GX_TF_I4     = 0x0
GX_TF_I8     = 0x1
GX_TF_IA4    = 0x2
GX_TF_IA8    = 0x3
GX_TF_RGB565 = 0x4
GX_TF_RGB5A3 = 0x5
GX_TF_RGBA8  = 0x6
GX_TF_CMPR   = 0xE

GX_CTF_R4    = 0x0 | _GX_TF_CTF
GX_CTF_RA4   = 0x2 | _GX_TF_CTF
GX_CTF_RA8   = 0x3 | _GX_TF_CTF
GX_CTF_YUVA8 = 0x6 | _GX_TF_CTF
GX_CTF_A8    = 0x7 | _GX_TF_CTF
GX_CTF_R8    = 0x8 | _GX_TF_CTF
GX_CTF_G8    = 0x9 | _GX_TF_CTF
GX_CTF_B8    = 0xA | _GX_TF_CTF
GX_CTF_RG8   = 0xB | _GX_TF_CTF
GX_CTF_GB8   = 0xC | _GX_TF_CTF

GX_TF_Z8     = 0x1 | _GX_TF_ZTF
GX_TF_Z16    = 0x3 | _GX_TF_ZTF
GX_TF_Z24X8  = 0x6 | _GX_TF_ZTF

GX_CTF_Z4    = 0x0 | _GX_TF_ZTF | _GX_TF_CTF
GX_CTF_Z8M   = 0x9 | _GX_TF_ZTF | _GX_TF_CTF
GX_CTF_Z8L   = 0xA | _GX_TF_ZTF | _GX_TF_CTF
GX_CTF_Z16L  = 0xC | _GX_TF_ZTF | _GX_TF_CTF

GX_TF_A8     = GX_CTF_A8


#GXTlutFmt
GX_TL_IA8    = 0x0
GX_TL_RGB565 = 0x1
GX_TL_RGB5A3 = 0x2
GX_MAX_TLUTFMT = 0x3


#GXTexMapID
GX_TEXMAP0 = 0
GX_TEXMAP1 = 1
GX_TEXMAP2 = 2
GX_TEXMAP3 = 3
GX_TEXMAP4 = 4
GX_TEXMAP5 = 5
GX_TEXMAP6 = 6
GX_TEXMAP7 = 7
GX_MAX_TEXMAP = 8

GX_TEXMAP_NULL = 0xff
GX_TEX_DISABLE = 0x100


#GXFogType
GX_FOG_NONE		     = 0x00

GX_FOG_PERSP_LIN     = 0x02
GX_FOG_PERSP_EXP     = 0x04
GX_FOG_PERSP_EXP2    = 0x05
GX_FOG_PERSP_REVEXP  = 0x06
GX_FOG_PERSP_REVEXP2 = 0x07

GX_FOG_ORTHO_LIN     = 0x0A
GX_FOG_ORTHO_EXP     = 0x0C
GX_FOG_ORTHO_EXP2    = 0x0D
GX_FOG_ORTHO_REVEXP  = 0x0E
GX_FOG_ORTHO_REVEXP2 = 0x0F

# For compatibility with former versions
GX_FOG_LIN 		= GX_FOG_PERSP_LIN
GX_FOG_EXP		= GX_FOG_PERSP_EXP
GX_FOG_EXP2		= GX_FOG_PERSP_EXP2
GX_FOG_REVEXP  	= GX_FOG_PERSP_REVEXP
GX_FOG_REVEXP2 	= GX_FOG_PERSP_REVEXP2

#GXBlendMode
GX_BM_NONE       = 0x0
GX_BM_BLEND      = 0x1
GX_BM_LOGIC      = 0x2
GX_BM_SUBTRACT   = 0x3
GX_MAX_BLENDMODE = 0x4

#GXBlendFactor
GX_BL_ZERO        = 0x0
GX_BL_ONE         = 0x1
GX_BL_SRCCLR      = 0x2
GX_BL_INVSRCCLR   = 0x3
GX_BL_SRCALPHA    = 0x4
GX_BL_INVSRCALPHA = 0x5
GX_BL_DSTALPHA    = 0x6
GX_BL_INVDSTALPHA = 0x7

GX_BL_DSTCLR    = GX_BL_SRCCLR
GX_BL_INVDSTCLR = GX_BL_INVSRCCLR

#GXCompare
GX_NEVER   = 0x0
GX_LESS    = 0x1
GX_EQUAL   = 0x2
GX_LEQUAL  = 0x3
GX_GREATER = 0x4
GX_NEQUAL  = 0x5
GX_GEQUAL  = 0x6
GX_ALWAYS  = 0x7

#GXLogicOp
GX_LO_CLEAR   = 0x0
GX_LO_AND     = 0x1
GX_LO_REVAND  = 0x2
GX_LO_COPY    = 0x3
GX_LO_INVAND  = 0x4
GX_LO_NOOP    = 0x5
GX_LO_XOR     = 0x6
GX_LO_OR      = 0x7
GX_LO_NOR     = 0x8
GX_LO_EQUIV   = 0x9
GX_LO_INV     = 0xA
GX_LO_REVOR   = 0xB
GX_LO_INVCOPY = 0xC
GX_LO_INVOR   = 0xD
GX_LO_NAND    = 0xE
GX_LO_SET     = 0xF
