"""Snapshot Blender cameras into BRCamera dataclasses.

Captures lens in mm, sensor height, clip planes, and Z-up positions in
Blender frame. Per-action keyframe series (location, lens, clip,
rotation, plus the target-empty's location) are also captured, raw, in
Blender units. Plan does the FOV conversion and the Z-up → Y-up axis
swap.
"""
import bpy

try:
    from .....shared.BR.cameras import BRCamera, BRCameraAnimation
    from .....shared.IR.animation import IRKeyframe
    from .....shared.IR.enums import Interpolation
    from .....shared.helpers.logger import StubLogger
except (ImportError, SystemError):
    from shared.BR.cameras import BRCamera, BRCameraAnimation
    from shared.IR.animation import IRKeyframe
    from shared.IR.enums import Interpolation
    from shared.helpers.logger import StubLogger


_INTERP_TO_IR = {
    'CONSTANT': Interpolation.CONSTANT,
    'LINEAR': Interpolation.LINEAR,
    'BEZIER': Interpolation.BEZIER,
}

# Names created by scripts/prepare_for_export.py's prepare_camera() —
# duplicated here because standalone scripts may not import plugin code.
_PREP_AUTO_CAMERA_NAMES = {"Debug_Camera"}


def describe_cameras(context, logger=StubLogger(), skip_prep_auto=False):
    """Read Blender camera objects into a BRCamera list.

    In: context (bpy.types.Context); logger; skip_prep_auto (bool — drop
        prep-script auto-generated debug cameras when writing bare .dat).
    Out: list[BRCamera].
    """
    out = []

    for obj in bpy.data.objects:
        if obj.type != 'CAMERA':
            continue
        if obj.hide_viewport or obj.hide_get():
            logger.debug("  Skipping camera '%s': hidden", obj.name)
            continue
        if skip_prep_auto and obj.name in _PREP_AUTO_CAMERA_NAMES:
            logger.debug("  Skipping camera '%s': auto-generated by prepare_for_export (.dat output)", obj.name)
            continue

        if obj.data.type not in ('PERSP', 'ORTHO'):
            logger.debug("  Skipping camera '%s': unsupported type '%s'", obj.name, obj.data.type)
            continue

        sensor_h = (obj.data.sensor_height
                    if obj.data.sensor_fit == 'VERTICAL' else 18.0)

        # For ORTHO, BR.lens carries ortho_scale (per BRCamera spec).
        lens = obj.data.ortho_scale if obj.data.type == 'ORTHO' else obj.data.lens

        target_obj = _track_to_target(obj)
        target_location = None
        if target_obj is not None:
            t = target_obj.location
            target_location = (t.x, t.y, t.z)

        loc = obj.location
        animations = _describe_camera_animations(obj, target_obj, sensor_h, logger)

        out.append(BRCamera(
            name=obj.name,
            projection=obj.data.type,  # 'PERSP' / 'ORTHO'
            lens=lens,
            sensor_height=sensor_h,
            clip_start=obj.data.clip_start,
            clip_end=obj.data.clip_end,
            aspect=obj.get("dat_camera_aspect", 1.333),
            location=(loc.x, loc.y, loc.z),
            target_location=target_location,
            animations=animations,
        ))

    if out:
        logger.info("  Described %d camera(s)", len(out))
    return out


def _track_to_target(obj):
    for constraint in obj.constraints:
        if constraint.type == 'TRACK_TO' and constraint.target:
            return constraint.target
    return None


def _describe_camera_animations(cam_obj, target_obj, sensor_h, logger):
    anim_data = cam_obj.animation_data
    if not anim_data or not anim_data.action:
        return []
    action = anim_data.action

    tracks = {
        'loc_x': _extract_fcurve(action, 'location', 0),
        'loc_y': _extract_fcurve(action, 'location', 1),
        'loc_z': _extract_fcurve(action, 'location', 2),
        'lens': _extract_fcurve(action, 'data.lens', 0),
        'roll': _extract_fcurve(action, 'rotation_euler', 2),
        'clip_start': _extract_fcurve(action, 'data.clip_start', 0),
        'clip_end': _extract_fcurve(action, 'data.clip_end', 0),
        'target_loc_x': [],
        'target_loc_y': [],
        'target_loc_z': [],
    }
    if target_obj and target_obj.animation_data and target_obj.animation_data.action:
        ta = target_obj.animation_data.action
        tracks['target_loc_x'] = _extract_fcurve(ta, 'location', 0)
        tracks['target_loc_y'] = _extract_fcurve(ta, 'location', 1)
        tracks['target_loc_z'] = _extract_fcurve(ta, 'location', 2)

    if not any(tracks.values()):
        return []

    end_frame = 0.0
    for keyframes in tracks.values():
        if keyframes:
            end_frame = max(end_frame, max(kf.frame for kf in keyframes))

    return [BRCameraAnimation(
        name=action.name,
        end_frame=end_frame,
        loop=False,
        **tracks,
    )]


def _extract_fcurve(action, data_path, index):
    fcurve = action.fcurves.find(data_path, index=index)
    if not fcurve or not fcurve.keyframe_points:
        return []

    keyframes = []
    for kp in fcurve.keyframe_points:
        keyframes.append(IRKeyframe(
            frame=kp.co[0],
            value=kp.co[1],
            interpolation=_INTERP_TO_IR.get(kp.interpolation, Interpolation.LINEAR),
        ))
    return keyframes
