"""Snapshot Blender lights into BRLight dataclasses.

Blender→BR only: keeps colours in linear RGB and positions in Z-up
Blender frame. The sRGB conversion and Y-up coordinate flip happen in
``plan/helpers/lights.py`` on the way to IR.
"""
import bpy

try:
    from .....shared.BR.lights import BRLight
    from .....shared.helpers.logger import StubLogger
except (ImportError, SystemError):
    from shared.BR.lights import BRLight
    from shared.helpers.logger import StubLogger


# Names created by scripts/prepare_for_export.py's prepare_lights() —
# duplicated here because standalone scripts may not import plugin code.
# Keep this set in sync with that script.
_PREP_AUTO_LIGHT_NAMES = {"Ambient_Light", "Main_Light", "Fill_Light", "Back_Light"}


def describe_lights(context, logger=StubLogger(), skip_prep_auto=False):
    """Read Blender light objects into a BRLight list.

    In: context (bpy.types.Context); logger; skip_prep_auto (bool — drop
        prep-script auto-generated battle lights when writing bare .dat).
    Out: list[BRLight].
    """
    out = []

    for obj in bpy.data.objects:
        if obj.type != 'LIGHT':
            continue
        if obj.hide_viewport or obj.hide_get():
            logger.debug("  Skipping light '%s': hidden", obj.name)
            continue
        if skip_prep_auto and obj.name in _PREP_AUTO_LIGHT_NAMES:
            logger.debug("  Skipping light '%s': auto-generated by prepare_for_export (.dat output)", obj.name)
            continue

        c = obj.data.color
        color = (c[0], c[1], c[2])  # linear; plan converts to sRGB

        # Ambient marker: explicit dat_light_type custom prop. Ambient
        # lights have no Blender equivalent — they're tagged on the
        # Blender side and resurrected as zero-energy POINT lights with
        # is_ambient=True.
        if obj.get('dat_light_type') == 'AMBIENT':
            out.append(BRLight(
                name=obj.name,
                blender_type='POINT',
                color=color,
                energy=0.0,
                is_ambient=True,
            ))
            continue

        if obj.data.type not in ('SUN', 'POINT', 'SPOT'):
            logger.debug("  Skipping light '%s': unsupported type '%s'", obj.name, obj.data.type)
            continue

        loc = obj.location
        location = (loc.x, loc.y, loc.z)
        target_location = _read_track_to_target(obj)

        # SUN with no TRACK_TO: derive direction from the light's forward
        # axis (object's −Z vector). Plan converts to IR position+target.
        if obj.data.type == 'SUN' and target_location is None:
            from mathutils import Vector
            forward = obj.matrix_world.to_quaternion() @ Vector((0, 0, -1))
            location = (0.0, 0.0, 0.0)
            target_location = (forward.x, forward.y, forward.z)

        out.append(BRLight(
            name=obj.name,
            blender_type=obj.data.type,
            color=color,
            energy=obj.data.energy,
            location=location,
            target_location=target_location,
            is_ambient=False,
        ))

    if out:
        logger.info("  Described %d light(s)", len(out))
    return out


def _read_track_to_target(obj):
    for constraint in obj.constraints:
        if constraint.type == 'TRACK_TO' and constraint.target:
            t = constraint.target.location
            return (t.x, t.y, t.z)
    return None
